// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ToServerData struct {
	Ctype                *string  `protobuf:"bytes,1,req,name=ctype" json:"ctype,omitempty"`
	Httpdata             []byte   `protobuf:"bytes,2,opt,name=httpdata" json:"httpdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToServerData) Reset()         { *m = ToServerData{} }
func (m *ToServerData) String() string { return proto.CompactTextString(m) }
func (*ToServerData) ProtoMessage()    {}
func (*ToServerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *ToServerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToServerData.Unmarshal(m, b)
}
func (m *ToServerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToServerData.Marshal(b, m, deterministic)
}
func (m *ToServerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToServerData.Merge(m, src)
}
func (m *ToServerData) XXX_Size() int {
	return xxx_messageInfo_ToServerData.Size(m)
}
func (m *ToServerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ToServerData.DiscardUnknown(m)
}

var xxx_messageInfo_ToServerData proto.InternalMessageInfo

func (m *ToServerData) GetCtype() string {
	if m != nil && m.Ctype != nil {
		return *m.Ctype
	}
	return ""
}

func (m *ToServerData) GetHttpdata() []byte {
	if m != nil {
		return m.Httpdata
	}
	return nil
}

type ResponseFromServer struct {
	Success              *bool    `protobuf:"varint,1,req,name=Success" json:"Success,omitempty"`
	TcpData              []byte   `protobuf:"bytes,2,opt,name=tcpData" json:"tcpData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFromServer) Reset()         { *m = ResponseFromServer{} }
func (m *ResponseFromServer) String() string { return proto.CompactTextString(m) }
func (*ResponseFromServer) ProtoMessage()    {}
func (*ResponseFromServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ResponseFromServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFromServer.Unmarshal(m, b)
}
func (m *ResponseFromServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFromServer.Marshal(b, m, deterministic)
}
func (m *ResponseFromServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFromServer.Merge(m, src)
}
func (m *ResponseFromServer) XXX_Size() int {
	return xxx_messageInfo_ResponseFromServer.Size(m)
}
func (m *ResponseFromServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFromServer.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFromServer proto.InternalMessageInfo

func (m *ResponseFromServer) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ResponseFromServer) GetTcpData() []byte {
	if m != nil {
		return m.TcpData
	}
	return nil
}

type RealUser struct {
	Username             *string  `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Nickname             *string  `protobuf:"bytes,2,req,name=Nickname" json:"Nickname,omitempty"`
	Avatar               *string  `protobuf:"bytes,3,req,name=Avatar" json:"Avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealUser) Reset()         { *m = RealUser{} }
func (m *RealUser) String() string { return proto.CompactTextString(m) }
func (*RealUser) ProtoMessage()    {}
func (*RealUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *RealUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealUser.Unmarshal(m, b)
}
func (m *RealUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealUser.Marshal(b, m, deterministic)
}
func (m *RealUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealUser.Merge(m, src)
}
func (m *RealUser) XXX_Size() int {
	return xxx_messageInfo_RealUser.Size(m)
}
func (m *RealUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RealUser.DiscardUnknown(m)
}

var xxx_messageInfo_RealUser proto.InternalMessageInfo

func (m *RealUser) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RealUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *RealUser) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

//User is login data
type User struct {
	Username             *string  `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=Password" json:"Password,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

//Info is for changing avatar data and nickname
type InfoWithUsername struct {
	Username             *string  `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Info                 []byte   `protobuf:"bytes,2,opt,name=Info" json:"Info,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoWithUsername) Reset()         { *m = InfoWithUsername{} }
func (m *InfoWithUsername) String() string { return proto.CompactTextString(m) }
func (*InfoWithUsername) ProtoMessage()    {}
func (*InfoWithUsername) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *InfoWithUsername) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoWithUsername.Unmarshal(m, b)
}
func (m *InfoWithUsername) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoWithUsername.Marshal(b, m, deterministic)
}
func (m *InfoWithUsername) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoWithUsername.Merge(m, src)
}
func (m *InfoWithUsername) XXX_Size() int {
	return xxx_messageInfo_InfoWithUsername.Size(m)
}
func (m *InfoWithUsername) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoWithUsername.DiscardUnknown(m)
}

var xxx_messageInfo_InfoWithUsername proto.InternalMessageInfo

func (m *InfoWithUsername) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *InfoWithUsername) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *InfoWithUsername) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ToServerData)(nil), "toServerData")
	proto.RegisterType((*ResponseFromServer)(nil), "ResponseFromServer")
	proto.RegisterType((*RealUser)(nil), "RealUser")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*InfoWithUsername)(nil), "InfoWithUsername")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xce, 0xc1, 0x4b, 0x85, 0x40,
	0x10, 0x06, 0x70, 0x9e, 0xbd, 0x57, 0x36, 0xf8, 0xea, 0xb1, 0x27, 0x8f, 0xe2, 0xc9, 0x53, 0xdd,
	0x82, 0x2e, 0x81, 0x20, 0x41, 0x97, 0x08, 0x2d, 0x3a, 0x0f, 0xeb, 0x84, 0x62, 0xee, 0x2c, 0xbb,
	0x93, 0xd1, 0x7f, 0x1f, 0xab, 0x46, 0x11, 0x75, 0x5a, 0xf6, 0x63, 0x7e, 0xdf, 0x0c, 0x40, 0x8b,
	0x82, 0x17, 0xd6, 0xb1, 0x70, 0x7e, 0x09, 0x89, 0x70, 0x43, 0x6e, 0x22, 0x57, 0xa1, 0xa0, 0xda,
	0xc3, 0x4e, 0xcb, 0x87, 0xa5, 0x74, 0x93, 0x45, 0xc5, 0xa9, 0x3a, 0x40, 0xdc, 0x89, 0xd8, 0x00,
	0xd2, 0x28, 0xdb, 0x14, 0x49, 0x7e, 0x05, 0xaa, 0x26, 0x6f, 0xd9, 0x78, 0xba, 0x75, 0x3c, 0x2e,
	0x54, 0x9d, 0xc3, 0x49, 0xf3, 0xa6, 0x35, 0x79, 0x3f, 0xc3, 0x38, 0x04, 0xa2, 0x6d, 0xf5, 0xed,
	0x6e, 0x20, 0xae, 0x09, 0x5f, 0x9f, 0x3c, 0xb9, 0xd0, 0x1a, 0x5e, 0x83, 0xe3, 0x8f, 0x3d, 0xf7,
	0xbd, 0x1e, 0xe6, 0x24, 0x9a, 0x93, 0x33, 0x38, 0x2e, 0x27, 0x14, 0x74, 0xe9, 0x51, 0xf8, 0xe7,
	0xd7, 0xb0, 0xfd, 0xdf, 0x3e, 0xa0, 0xf7, 0xef, 0xec, 0xda, 0xd5, 0xee, 0x61, 0xf7, 0xc8, 0x03,
	0x99, 0x95, 0x96, 0x70, 0xb8, 0x33, 0x2f, 0xfc, 0xdc, 0x4b, 0xf7, 0x45, 0xff, 0xa8, 0x49, 0x60,
	0x1b, 0xa6, 0x96, 0x73, 0x7f, 0x55, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x22, 0xef, 0x50, 0xb9,
	0x33, 0x01, 0x00, 0x00,
}
